### ISSUE TITLE
just support macOS?

### ISSUE THREAD

**Issue by myyan** [loomnetwork/solidity-social-example#1]
![image](https://user-images.githubusercontent.com/10210390/40832369-bc8032c4-65bd-11e8-914e-8d1748ec35c6.png)

i want to build it on the ubuntu ,can you support it ?

**Comment by mattkanwisher** [comment]
sure we will add docs for that soon

in mean time you can try using apt

apt install elasticsearch
apt install redis

also change any download urls on wget from /osx/ to /linux/

**Comment by myyan** [comment]
yeah , thank  ! I will have a try.

**Comment by myyan** [comment]
- hi ,when i run follow command , encountered this error
![image](https://user-images.githubusercontent.com/10210390/40905243-ec504152-680f-11e8-9804-36b59c73238d.png)

- and the package.json  just `start` command
![image](https://user-images.githubusercontent.com/10210390/40905341-2b15a99a-6810-11e8-8df1-c871b9260753.png)

**Comment by mattkanwisher** [comment]
https://loomx.io/developers/docs/en/prereqs-ubuntu.html

make sure you install all of them
```bash
export PROTOBUF_VERSION=3.5.1
curl -OL https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-linux-x86_64.zip
sudo unzip protoc-${PROTOBUF_VERSION}-linux-x86_64.zip -d /usr/local
sudo chmod +x /usr/local/bin/protoc
```

**Comment by myyan** [comment]
thank you , i will read the sdk  documentation

**Comment by myyan** [comment]
![image](https://user-images.githubusercontent.com/10210390/40964787-904bb86c-68de-11e8-862b-37eacd9317d2.png)

**Comment by eduardonunesp** [comment]
Hey @myyan thanks for the report, I'll check that, meanwhile could you please inform versions used for node and sdk

**Comment by eduardonunesp** [comment]
Hi @myyan I'm only able to reproduce this error if the `loom` binary not executed, or if unreachable, could you please check if the `loom` started correctly ?

**Comment by myyan** [comment]
@eduardonunesp 
### This is my snapshot
![image](https://user-images.githubusercontent.com/10210390/41017327-0a0bbcda-6987-11e8-9acb-02aecf414652.png)


![image](https://user-images.githubusercontent.com/10210390/41017378-34229098-6987-11e8-8312-a8ade5acdecf.png)

![image](https://user-images.githubusercontent.com/10210390/41017405-4bfaf8ea-6987-11e8-8389-408e7da23654.png)

![image](https://user-images.githubusercontent.com/10210390/41017415-53185d2a-6987-11e8-8ff3-8649ae7a9f12.png)

**Comment by mattkanwisher** [comment]
The indexer is failing cause it looks like it can't connect to the dappchain, you should try and restart it

**Comment by eduardonunesp** [comment]
There's a updates on the repo for the project too @myyan maybe it can help to debug

**Comment by myyan** [comment]
@mattkanwisher @eduardonunesp now it's work fine , thank you

**Comment by eduardonunesp** [comment]
Awesome @myyan thanks for your report and patience
